/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.controller.CorteZ;
import com.controller.CorteZAspelCaja;
import com.controller.ReporteFiscalController;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Currency;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Copper
 */
public class ReporteFiscal extends javax.swing.JFrame {

    /**
     * Creates new form ReporteFiscal
     */
    public ReporteFiscal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfecha = new com.toedter.calendar.JCalendar();
        btnsalir = new javax.swing.JButton();
        btnaceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnsalir.setBackground(new java.awt.Color(255, 51, 51));
        btnsalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setText("Salir");
        btnsalir.setBorder(null);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btnaceptar.setBackground(new java.awt.Color(0, 204, 204));
        btnaceptar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnaceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnaceptar.setText("Aceptar");
        btnaceptar.setBorder(null);
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Fecha Corte:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(btnaceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        double granTotal = 0;
        double totalVentaandAbonos = 0;
        String nCorte = "";
        Locale usa = new Locale("en", "US");
        Currency dollars = Currency.getInstance(usa);
        NumberFormat dollarFormat = NumberFormat.getCurrencyInstance(usa);
        ReporteFiscalController rmodel;
        CorteZAspelCaja corteCaja;
        String datevar2 = "";
        String monthvar2 = "";
        CorteZ cz = new CorteZ();
        Calendar cal = jfecha.getCalendar();
        int datevar = cal.get(Calendar.DATE);
        int monthvar = cal.get(Calendar.MONTH);
        int yearvar = cal.get(Calendar.YEAR);
        
        monthvar = monthvar+1;
        
        if(datevar < 10){
            datevar2 = datevar+"";
            datevar2 = "0"+datevar2;
        }else { datevar2 = datevar+""; }
        
        if (monthvar < 10){
            monthvar2 = monthvar+"";
            monthvar2 = "0"+monthvar2;
        }else { monthvar2 = monthvar+"";}
        
        String fecha = datevar2+"/"+monthvar2+"/"+yearvar;
        
        try{
            String path = System.getProperty("user.dir")+"/ReporteFiscal.jasper";
            HashMap parametros = new HashMap();
            rmodel = new ReporteFiscalController();
            corteCaja = new CorteZAspelCaja();
            double ventas, impuesto, iva, totalimpuesto, totalcobro, abonos, impuestoabono;
            
            if (rmodel.getVentas(fecha).isEmpty()){
                ventas = 0;
                JOptionPane.showMessageDialog(null, "");
            }else {ventas = rmodel.getVentas(fecha).get(0).getVentas();}
           
            if (rmodel.getImpuesto(fecha).isEmpty()){impuesto = 0;}
            else{impuesto = rmodel.getImpuesto(fecha).get(0).getImpuesto();}
            
            if (rmodel.getIva(fecha).isEmpty()){iva = 0;}
            else{iva = rmodel.getIva(fecha).get(0).getIva();}
            
            if (corteCaja.getAbonoSae(fecha).isEmpty()){
                abonos = 0;
                impuestoabono = 0;
                JOptionPane.showMessageDialog(null, "");
            }else{
                abonos = corteCaja.getAbonoSae(fecha).get(0).getAbonoSae();
                impuestoabono = corteCaja.getAbonoSae(fecha).get(0).getImpuestoabono();
            }
            
            
            //impuesto = impuesto * 0.08;
            impuestoabono = impuestoabono * 0.25;
            totalimpuesto = (impuesto) + (iva) + (impuestoabono);
            double inpmenos = totalimpuesto * 0.08;
            ventas = (ventas) + (abonos) - (totalimpuesto) - (impuestoabono);
            totalcobro = (totalimpuesto) + (ventas) + (impuestoabono);

            System.out.println(impuestoabono);
            
            parametros.put("ventas", dollarFormat.format(ventas+impuestoabono));
            parametros.put("fecha", fecha);
            parametros.put("impuesto", dollarFormat.format(totalimpuesto * 0.08));
            parametros.put("iva", dollarFormat.format(impuestoabono - inpmenos));
            parametros.put("totalimpuesto", dollarFormat.format(totalimpuesto+impuesto));
            parametros.put("totalcobro", dollarFormat.format(totalcobro));
            
            JasperPrint jprint = JasperFillManager.fillReport(path, parametros, new JREmptyDataSource());
            JasperViewer viewer = new JasperViewer(jprint, false);
            viewer.setVisible(true);
        }catch(JRException e){ 
            System.out.print(e.toString());
        } catch (SQLException ex) {
            Logger.getLogger(ReporteFiscal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnaceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteFiscal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JCalendar jfecha;
    // End of variables declaration//GEN-END:variables
}
